// Reproducible release evidence; never repairs or overwrites dependency sources.
import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync} from 'node:fs';
import {execFileSync,spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
const read=p=>JSON.parse(readFileSync(p,'utf8')),hash=b=>createHash('sha256').update(b).digest('hex');
const run=(p,a)=>execFileSync(p,a,{encoding:'utf8'}).trim();
const pkg=read('package.json'),lock=read('package-lock.json');
const version=pkg.version,kennel=readFileSync('kennel.toml','utf8'),readme=readFileSync('README.md','utf8'),changelog=readFileSync('CHANGELOG.md','utf8');
if(!/^\d+\.\d+\.\d+$/.test(version)||lock.version!==version||lock.packages[''].version!==version||kennel.match(/^version = "([^"]+)"/m)?.[1]!==version||!readme.includes(`version-${version}-black`)||!changelog.includes(`## ${version} — `))throw Error('Release version differs across manifests, README, or changelog');
if(!kennel.includes('"patches"'))throw Error('Kennel package must include its pinned browser source correction');
const deps=read('dependencies.json'),report={project:{name:pkg.name,version,tag:`v${version}`},dependencies:[],bundles:[],licenses:[],audit:null};
for(const [name,dep] of Object.entries(deps)) {
 const path=`.deps/${name==='sitekit'?'site-kit':name}`;
 if(run('git',['-C',path,'rev-parse','HEAD'])!==dep.commit||run('git',['-C',path,'status','--porcelain'])) throw Error(`${name}: dependency revision or working tree differs`);
 report.dependencies.push({name,...dep});
}
for(const [file,source] of [['motion-mini.js','export { animate } from "motion/mini";'],['motion-hybrid.js','export { animate, stagger, frame } from "motion";']]){
 const result=await build({stdin:{contents:source,resolveDir:process.cwd()},bundle:true,minify:true,format:'esm',platform:'browser',target:'es2022',write:false,banner:{js:'/* Motion 13.4.6 (MIT). Generated by npm run bundle:motion. */'}});
 const actual=readFileSync(`vendor/motion/${file}`);
 if(!actual.equals(Buffer.from(result.outputFiles[0].contents)))throw Error(`Regenerate ${file}`);
 report.bundles.push({file,bytes:actual.length,sha256:hash(actual)});
}
for(const [path,pkg] of Object.entries(read('package-lock.json').packages)) {
 if(!path)continue;
 const installed=existsSync(`${path}/package.json`)?read(`${path}/package.json`):pkg;
 if(installed.version!==pkg.version)throw Error(`Installed version differs from lockfile: ${path}`);
 const license=installed.license||pkg.license;
 if(!license)throw Error(`Missing license declaration: ${path}`);
 report.licenses.push({path,version:pkg.version,license,integrity:pkg.integrity});
}
let mediaBytes=0;
report.media=[];
for(const item of read('examples/reference/assets/media-sources.json')) {
 const data=readFileSync(`examples/reference/assets/${item.file}`);
 if(hash(data)!==item.sha256||data.length!==item.bytes)throw Error(`Media provenance mismatch: ${item.file}`);
 if(!item.file.endsWith('.webp')||data.toString('ascii',0,4)!=='RIFF'||data.toString('ascii',8,12)!=='WEBP')throw Error(`Reference artwork must be WebP: ${item.file}`);
 if(data.length>200*1024)throw Error(`Reference image exceeds 200 KiB: ${item.file}`);
 mediaBytes+=data.length;
 report.media.push({file:item.file,bytes:data.length,sha256:item.sha256});
}
if(mediaBytes>400*1024)throw Error('Reference artwork exceeds the combined 400 KiB budget');
for(const [copy,source] of [['vendor/motion/LICENSE.md','node_modules/motion/LICENSE.md'],['vendor/motion/LICENSE-framer-motion.md','node_modules/framer-motion/LICENSE.md']])if(!readFileSync(copy).equals(readFileSync(source)))throw Error(`License copy differs: ${copy}`);
report.distributedLicenseFiles=['assets/licenses/Inter-OFL.txt','assets/licenses/BreeSerif-OFL.txt','.deps/site-kit/dist/LICENSE','.deps/site-kit/dist/fonts/DepartureMono-LICENSE.txt','.deps/site-kit/dist/icons/LICENSE.txt','examples/arabic/assets/OFL.txt','vendor/motion/LICENSE.md','vendor/motion/LICENSE-framer-motion.md'].map(file=>({file,sha256:hash(readFileSync(file))}));
const audit=spawnSync('npm',['audit','--json'],{encoding:'utf8'});
if(audit.error)throw audit.error;
report.audit=JSON.parse(audit.stdout);
mkdirSync('docs/evidence',{recursive:true});writeFileSync('docs/evidence/release-dependencies.json',JSON.stringify(report,null,2)+'\n');
if(audit.status!==0)throw Error('Advisory check failed; inspect docs/evidence/release-dependencies.json');
console.log(`Release checks passed: ${report.dependencies.length} pins, ${report.bundles.length} reproducible bundles, ${report.licenses.length} package licenses, media hashes, no reported npm advisories.`);
