// Reproducible release evidence; never repairs or overwrites dependency sources.
import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync} from 'node:fs';
import {execFileSync,spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
const read=p=>JSON.parse(readFileSync(p,'utf8')),hash=b=>createHash('sha256').update(b).digest('hex');
const run=(p,a)=>execFileSync(p,a,{encoding:'utf8'}).trim();
const deps=read('dependencies.json'),report={dependencies:[],bundles:[],licenses:[],audit:null};
for(const [name,dep] of Object.entries(deps)) {
 const path=`.deps/${name==='sitekit'?'site-kit':name}`;
 if(run('git',['-C',path,'rev-parse','HEAD'])!==dep.commit||run('git',['-C',path,'status','--porcelain'])) throw Error(`${name}: dependency revision or working tree differs`);
 report.dependencies.push({name,...dep});
}
for(const [file,source] of [['motion-mini.js','export { animate } from "motion/mini";'],['motion-hybrid.js','export { animate, stagger, frame } from "motion";']]){
 const result=await build({stdin:{contents:source,resolveDir:process.cwd()},bundle:true,minify:true,format:'esm',platform:'browser',target:'es2022',write:false,banner:{js:'/* Motion 13.4.6 (MIT). Generated by npm run bundle:motion. */'}});
 const actual=readFileSync(`vendor/motion/${file}`);
 if(!actual.equals(Buffer.from(result.outputFiles[0].contents)))throw Error(`Regenerate ${file}`);
 report.bundles.push({file,bytes:actual.length,sha256:hash(actual)});
}
for(const [path,pkg] of Object.entries(read('package-lock.json').packages)) {
 if(!path)continue;
 const installed=existsSync(`${path}/package.json`)?read(`${path}/package.json`):pkg;
 if(installed.version!==pkg.version)throw Error(`Installed version differs from lockfile: ${path}`);
 const license=installed.license||pkg.license;
 if(!license)throw Error(`Missing license declaration: ${path}`);
 report.licenses.push({path,version:pkg.version,license,integrity:pkg.integrity});
}
for(const item of read('examples/reference/assets/media-sources.json'))if(hash(readFileSync(`examples/reference/assets/${item.file}`))!==item.sha256)throw Error(`Media provenance mismatch: ${item.file}`);
for(const [copy,source] of [['vendor/motion/LICENSE.md','node_modules/motion/LICENSE.md'],['vendor/motion/LICENSE-framer-motion.md','node_modules/framer-motion/LICENSE.md']])if(!readFileSync(copy).equals(readFileSync(source)))throw Error(`License copy differs: ${copy}`);
report.distributedLicenseFiles=['assets/licenses/Inter-OFL.txt','assets/licenses/BreeSerif-OFL.txt','.deps/site-kit/dist/LICENSE','.deps/site-kit/dist/fonts/DepartureMono-LICENSE.txt','.deps/site-kit/dist/icons/LICENSE.txt','examples/arabic/assets/OFL.txt','vendor/motion/LICENSE.md','vendor/motion/LICENSE-framer-motion.md'].map(file=>({file,sha256:hash(readFileSync(file))}));
const audit=spawnSync('npm',['audit','--json'],{encoding:'utf8'});
if(audit.error)throw audit.error;
report.audit=JSON.parse(audit.stdout);
mkdirSync('docs/evidence',{recursive:true});writeFileSync('docs/evidence/release-dependencies.json',JSON.stringify(report,null,2)+'\n');
if(audit.status!==0)throw Error('Advisory check failed; inspect docs/evidence/release-dependencies.json');
console.log(`Release checks passed: ${report.dependencies.length} pins, ${report.bundles.length} reproducible bundles, ${report.licenses.length} package licenses, media hashes, no reported npm advisories.`);
